In [133]:
import numpy as np 
import pretty_midi
import h5py
import os
import pandas as pd
from random import randrange,random

In [83]:
f = h5py.File(os.getcwd()+'/'+"000000014_t9_82.hdf5", 'r')
s=np.array(f['data'])
s=s[:32]


In [84]:
s.shape

(32, 129, 32)

In [85]:

s = np.concatenate(tuple(s),axis=1)
df = pd.DataFrame(s)
df.to_csv('s2.csv')

In [86]:
s.shape

(129, 1024)

In [90]:
for i in range(len(s))[:-1]:
    s[i]=s[i]+s[-1]
    #对于该行的每一个单位，如果是2，则替换成音高数字，也就是该行的行数
    for j in range(len(s[i])):
        if s[i][j] == 2:
            s[i][j] = i

In [91]:
df = pd.DataFrame(s)
df.to_csv('s3.csv')

In [139]:
random()<=0.15

True

In [140]:
a = np.arange(10).reshape(2,5)

In [141]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [142]:
a.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [143]:
len(a)

2

In [144]:
len(a.T)

5

In [145]:
b = np.arange(5)

In [146]:
len(b)

5

In [147]:
a[-1]

array([5, 6, 7, 8, 9])

In [148]:
b = a [-1]

In [149]:
b

array([5, 6, 7, 8, 9])

In [154]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [162]:
a = np.array([0,1])
b = np.array([1,1])

In [164]:
np.array([2 if a[i]==b[i] else 0 for i in range(len(a))])

array([0, 2])

In [165]:
def aaa(a):
    a[0]=5

In [166]:
aaa(a)

In [167]:
a

array([5, 1])

In [169]:
b = a

In [170]:
b[1] = 7

In [171]:
a

array([5, 7])

In [172]:
a

array([5, 7])

In [173]:
a = np.arange(10).reshape(2,5)

In [174]:
b = np.arange(10).reshape(2,5)

In [175]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [176]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [177]:
a+b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [178]:
a.shape

(2, 5)

In [179]:
len(a.shape)

2

In [181]:
a = np.arange(8)

In [184]:
[1 if a[j] == 2 else a[j] for j in range(len(a))]

[0, 1, 1, 3, 4, 5, 6, 7]

In [186]:
for i in np.arange(128):
    print(pretty_midi.program_to_instrument_name(i))

Acoustic Grand Piano
Bright Acoustic Piano
Electric Grand Piano
Honky-tonk Piano
Electric Piano 1
Electric Piano 2
Harpsichord
Clavinet
Celesta
Glockenspiel
Music Box
Vibraphone
Marimba
Xylophone
Tubular Bells
Dulcimer
Drawbar Organ
Percussive Organ
Rock Organ
Church Organ
Reed Organ
Accordion
Harmonica
Tango Accordion
Acoustic Guitar (nylon)
Acoustic Guitar (steel)
Electric Guitar (jazz)
Electric Guitar (clean)
Electric Guitar (muted)
Overdriven Guitar
Distortion Guitar
Guitar Harmonics
Acoustic Bass
Electric Bass (finger)
Electric Bass (pick)
Fretless Bass
Slap Bass 1
Slap Bass 2
Synth Bass 1
Synth Bass 2
Violin
Viola
Cello
Contrabass
Tremolo Strings
Pizzicato Strings
Orchestral Harp
Timpani
String Ensemble 1
String Ensemble 2
Synth Strings 1
Synth Strings 2
Choir Aahs
Voice Oohs
Synth Choir
Orchestra Hit
Trumpet
Trombone
Tuba
Muted Trumpet
French Horn
Brass Section
Synth Brass 1
Synth Brass 2
Soprano Sax
Alto Sax
Tenor Sax
Baritone Sax
Oboe
English Horn
Bassoon
Clarinet
Piccolo
Flut